import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'uk' | 'en' | 'pl';

interface LanguageStore {
    language: Language;
    setLanguage: (lang: Language) => void;
}

export const translations = {
    uk: {
        nav: {
            catalog: 'Каталог',
            bags: 'Сумки',
            wallets: 'Гаманці',
            belts: 'Ремені',
            accessories: 'Аксесуари',
            about: 'Про нас',
        },
        auth: {
            login: 'Увійти',
            register: 'Реєстрація',
            logout: 'Вийти',
            profile: 'Мій профіль',
            admin: 'Адмін панель',
        },
        login: {
            title: 'Вхід',
            subtitle: 'Раді бачити вас знову!',
            email: 'Email',
            password: 'Пароль',
            submit: 'Увійти',
            noAccount: 'Немає акаунту?',
            createAccount: 'Зареєструватись',
        },
        register: {
            title: 'Реєстрація',
            subtitle: 'Створіть свій акаунт',
            firstName: "Ім'я",
            lastName: 'Прізвище',
            email: 'Email',
            password: 'Пароль',
            confirmPassword: 'Підтвердіть пароль',
            submit: 'Зареєструватись',
            hasAccount: 'Вже є акаунт?',
            loginLink: 'Увійти',
            minPassword: 'Мінімум 6 символів',
            repeatPassword: 'Повторіть пароль',
        },
        cart: {
            cart: 'Кошик',
            empty: 'Кошик порожній',
            checkout: 'Оформити замовлення',
            total: 'Разом',
            clear: 'Очистити кошик',
            continue: 'Продовжити покупки',
        },
        checkout: {
            title: 'Оформлення замовлення',
            contactInfo: 'Контактні дані',
            firstName: "Ім'я",
            lastName: 'Прізвище',
            middleName: 'По батькові',
            email: 'Email',
            phone: 'Телефон',
            delivery: 'Доставка (Нова Пошта)',
            city: 'Місто',
            cityPlaceholder: 'Почніть вводити назву міста...',
            warehouse: 'Відділення',
            warehouseSelect: 'Оберіть відділення',
            payment: 'Оплата',
            paymentCod: 'Оплата при отриманні',
            paymentCard: 'Оплата карткою (Stripe)',
            yourOrder: 'Ваше замовлення',
            toPay: 'До сплати',
            submit: 'Підтвердити замовлення',
            processing: 'Обробка...',
            savedDataTitle: 'Дані з вашого профілю',
            savedDataMessage: 'Перевірте, будь ласка, правильність та актуальність даних',
        },
        profile: {
            personalData: 'Особисті дані',
            firstName: "Ім'я",
            lastName: 'Прізвище',
            email: 'Email',
            phone: 'Телефон',
            save: 'Зберегти зміни',
            orders: 'Замовлення',
            security: 'Безпека',
            shippingAddress: 'Адреса доставки',
            savedCity: 'Збережене місто',
            savedWarehouse: 'Збережене відділення',
            noOrders: 'Замовлень поки немає',
            orderNumber: 'Замовлення',
        },
        product: {
            addToCart: 'Додати в кошик',
            outOfStock: 'Немає в наявності',
            inStock: 'В наявності',
            color: 'Колір',
            description: 'Опис',
        },
        catalog: {
            title: 'Каталог товарів',
            subtitle: 'Вироби ручної роботи з натуральної шкіри',
            search: 'Пошук товарів...',
            filters: 'Фільтри',
            categories: 'Категорії',
            categoryBags: 'Сумки',
            categoryWallets: 'Гаманці',
            categoryAccessories: 'Аксесуари',
            categoryBelts: 'Ремені',
            colors: 'Колір',
            price: 'Ціна',
            from: 'Від',
            to: 'До',
            apply: 'Застосувати',
            reset: 'Скинути',
            found: 'Знайдено',
            products: 'товарів',
            sortNew: 'Новинки',
            sortPriceAsc: 'Від дешевих',
            sortPriceDesc: 'Від дорогих',
            sortName: 'За назвою А-Я',
            noProducts: 'Товарів не знайдено',
        },
        common: {
            loading: 'Завантаження...',
            save: 'Зберегти',
            cancel: 'Скасувати',
            delete: 'Видалити',
            edit: 'Редагувати',
            currency: 'грн',
        },
        about: {
            title: 'Про Leder',
            story: 'Наша історія',
            values: 'Наші цінності',
            quality: 'Якість',
            craftsmanship: 'Майстерність',
        },
        footer: {
            tagline: "Вироби зі шкіри ручної роботи. Створено з любов'ю в Україні.",
            catalog: 'Каталог',
            bags: 'Сумки',
            wallets: 'Гаманці',
            belts: 'Ремені',
            accessories: 'Аксесуари',
            information: 'Інформація',
            about: 'Про нас',
            delivery: 'Доставка та оплата',
            returns: 'Повернення',
            support: 'Підтримка',
            contacts: 'Контакти',
            location: 'Київ, Україна',
            rights: 'Всі права захищено.',
        },
        reviews: {
            reviews: 'Відгуки',
            reviewsCount: 'відгуків',
            writeReview: 'Написати відгук',
            yourRating: 'Ваша оцінка',
            yourComment: 'Ваш коментар',
            commentPlaceholder: 'Поділіться вашими враженнями...',
            selectRating: 'Оберіть оцінку',
            writeComment: 'Напишіть коментар',
            reviewSubmitted: 'Відгук додано!',
            questionSubmitted: 'Питання надіслано!',
            optional: "необов'язково",
            willBeQuestion: 'Без оцінки = Питання',
            yourQuestion: 'Ваше питання',
            questionPlaceholder: 'Задайте питання про товар...',
            submit: 'Надіслати',
            reply: 'Відповісти',
            replyPlaceholder: 'Ваша відповідь...',
            replyAdded: 'Відповідь додано',
            send: 'Надіслати',
            loginToReview: 'Увійдіть щоб залишити відгук',
            loginToLike: 'Увійдіть щоб поставити лайк',
            noReviews: 'Відгуків поки немає. Будьте першим!',
            confirmDelete: 'Видалити відгук?',
            deleted: 'Видалено',
            new: 'Новий',
            read: 'Прочитаний',
            replied: 'З відповіддю',
            markAsRead: 'Позначити прочитаним',
        },
        admin: {
            title: 'Адмін-панель',
            dashboard: 'Головна',
            products: 'Товари',
            categories: 'Категорії',
            orders: 'Замовлення',
            users: 'Користувачі',
            backToSite: 'На сайт',
            // Products
            addProduct: 'Додати товар',
            editProduct: 'Редагувати товар',
            searchProducts: 'Пошук товарів...',
            productCount: 'товарів',
            variant: 'Варіант',
            variants: 'Варіанти',
            addVariant: '+ Додати варіант',
            color: 'Колір',
            colorHex: 'HEX',
            stock: 'Залишок',
            lowStock: 'Мало на складі',
            images: 'Зображення',
            description: 'Опис',
            // Categories
            addCategory: 'Додати категорію',
            editCategory: 'Редагувати категорію',
            categoryName: 'Назва категорії',
            slug: 'Slug',
            // Orders
            orderNumber: 'Номер',
            client: 'Клієнт',
            phone: 'Телефон',
            city: 'Місто',
            amount: 'Сума',
            date: 'Дата',
            details: 'Деталі',
            orderDetails: 'Деталі замовлення',
            customer: 'Клієнт',
            delivery: 'Доставка',
            items: 'Товари',
            allStatuses: 'Всі статуси',
            statusNew: 'Новий',
            statusReceived: 'Отримано',
            statusShipped: 'Відправлено',
            statusDelivered: 'Доставлено',
            statusCancelled: 'Скасовано',
            // Users
            searchUsers: 'Пошук за email, ім\'ям...',
            user: 'Користувач',
            email: 'Email',
            role: 'Роль',
            registrationDate: 'Дата реєстрації',
            all: 'Всі',
            admins: 'Адміни',
            customers: 'Клієнти',
            roleAdmin: 'Адмін',
            roleCustomer: 'Клієнт',
            makeAdmin: 'Зробити адміном',
            removeAdmin: 'Забрати права',
            // Dashboard stats
            total: 'Всього',
            newOrders: 'Нових замовлень',
            totalProducts: 'Товарів',
            totalUsers: 'Користувачів',
            totalRevenue: 'Дохід',
            recentOrders: 'Останні замовлення',
            // Common
            productName: 'Назва товару',
            price: 'Ціна',
            category: 'Категорія',
            status: 'Статус',
            actions: 'Дії',
            search: 'Пошук...',
            save: 'Зберегти',
            cancel: 'Скасувати',
            delete: 'Видалити',
            close: 'Закрити',
            noData: 'Немає даних',
        },
        home: {
            heroTitle: "Створено з любов'ю до деталей",
            heroSubtitle: 'Шкіряні вироби ручної роботи преміум якості',
            viewCatalog: 'Переглянути каталог',
            categories: 'Категорії',
            bags: 'Сумки',
            wallets: 'Гаманці',
            belts: 'Ремені',
            accessories: 'Аксесуари',
            freeDelivery: 'Безкоштовна доставка',
            freeDeliveryDesc: 'При замовленні від 2000₴',
            warranty: 'Гарантія 2 роки',
            warrantyDesc: 'На всі вироби',
            handmade: 'Ручна робота',
            handmadeDesc: 'Кожен виріб унікальний',
            premiumQuality: 'Преміум якість',
            premiumQualityDesc: 'Тільки натуральна шкіра',
            qualityTradition: 'Традиції якості',
            qualityTraditionDesc: 'Понад 10 років досвіду в створенні преміальних шкіряних виробів',
            satisfiedClients: 'Задоволених клієнтів',
            naturalLeather: 'Натуральна шкіра',
            warrantyYears: 'Гарантії',
            aboutTitle: 'Про Leder',
            aboutText1: 'Ми — українська майстерня, яка створює вироби зі шкіри найвищої якості. Кожен виріб виготовляється вручну з увагою до найменших деталей.',
            aboutText2: 'Використовуємо тільки натуральну шкіру італійського та українського дублення. Наші вироби служать роками, набуваючи з часом благородної патини.',
            feature1: 'Натуральна шкіра',
            feature2: 'Ручна робота',
            feature3: 'Гарантія якості',
            feature4: 'Доставка по Україні',
            learnMore: 'Дізнатися більше',
            reviews: 'Відгуки клієнтів',
            ctaTitle: 'Готові зробити замовлення?',
            ctaSubtitle: 'Переглядайте каталог та обирайте найкраще',
            goToCatalog: 'Перейти до каталогу',
        },
    },
    en: {
        nav: {
            catalog: 'Catalog',
            bags: 'Bags',
            wallets: 'Wallets',
            belts: 'Belts',
            accessories: 'Accessories',
            about: 'About Us',
        },
        auth: {
            login: 'Login',
            register: 'Register',
            logout: 'Logout',
            profile: 'My Profile',
            admin: 'Admin Panel',
        },
        login: {
            title: 'Login',
            subtitle: 'Welcome back!',
            email: 'Email',
            password: 'Password',
            submit: 'Sign In',
            noAccount: "Don't have an account?",
            createAccount: 'Create account',
        },
        register: {
            title: 'Registration',
            subtitle: 'Create your account',
            firstName: 'First Name',
            lastName: 'Last Name',
            email: 'Email',
            password: 'Password',
            confirmPassword: 'Confirm Password',
            submit: 'Register',
            hasAccount: 'Already have an account?',
            loginLink: 'Sign in',
            minPassword: 'Minimum 6 characters',
            repeatPassword: 'Repeat password',
        },
        cart: {
            cart: 'Cart',
            empty: 'Cart is empty',
            checkout: 'Checkout',
            total: 'Total',
            clear: 'Clear cart',
            continue: 'Continue shopping',
        },
        checkout: {
            title: 'Checkout',
            contactInfo: 'Contact Information',
            firstName: 'First Name',
            lastName: 'Last Name',
            middleName: 'Middle Name',
            email: 'Email',
            phone: 'Phone',
            delivery: 'Delivery (Nova Poshta)',
            city: 'City',
            cityPlaceholder: 'Start typing city name...',
            warehouse: 'Warehouse',
            warehouseSelect: 'Select warehouse',
            payment: 'Payment',
            paymentCod: 'Cash on Delivery',
            paymentCard: 'Card Payment (Stripe)',
            yourOrder: 'Your Order',
            toPay: 'Total',
            submit: 'Confirm Order',
            processing: 'Processing...',
            savedDataTitle: 'Data from your profile',
            savedDataMessage: 'Please verify the accuracy and relevance of the information',
        },
        profile: {
            personalData: 'Personal Data',
            firstName: 'First Name',
            lastName: 'Last Name',
            email: 'Email',
            phone: 'Phone',
            save: 'Save Changes',
            orders: 'Orders',
            security: 'Security',
            shippingAddress: 'Shipping Address',
            savedCity: 'Saved City',
            savedWarehouse: 'Saved Warehouse',
            noOrders: 'No orders yet',
            orderNumber: 'Order',
        },
        product: {
            addToCart: 'Add to Cart',
            outOfStock: 'Out of Stock',
            inStock: 'In Stock',
            color: 'Color',
            description: 'Description',
        },
        catalog: {
            title: 'Product Catalog',
            subtitle: 'Handmade genuine leather products',
            search: 'Search products...',
            filters: 'Filters',
            categories: 'Categories',
            categoryBags: 'Bags',
            categoryWallets: 'Wallets',
            categoryAccessories: 'Accessories',
            categoryBelts: 'Belts',
            colors: 'Color',
            price: 'Price',
            from: 'From',
            to: 'To',
            apply: 'Apply',
            reset: 'Reset',
            found: 'Found',
            products: 'products',
            sortNew: 'Newest',
            sortPriceAsc: 'Price: Low to High',
            sortPriceDesc: 'Price: High to Low',
            sortName: 'Name A-Z',
            noProducts: 'No products found',
        },
        common: {
            loading: 'Loading...',
            save: 'Save',
            cancel: 'Cancel',
            delete: 'Delete',
            edit: 'Edit',
            currency: 'UAH',
        },
        about: {
            title: 'About Leder',
            story: 'Our Story',
            values: 'Our Values',
            quality: 'Quality',
            craftsmanship: 'Craftsmanship',
        },
        footer: {
            tagline: 'Handcrafted leather goods. Made with love in Ukraine.',
            catalog: 'Catalog',
            bags: 'Bags',
            wallets: 'Wallets',
            belts: 'Belts',
            accessories: 'Accessories',
            information: 'Information',
            about: 'About Us',
            delivery: 'Delivery & Payment',
            returns: 'Returns',
            support: 'Support',
            contacts: 'Contacts',
            location: 'Kyiv, Ukraine',
            rights: 'All rights reserved.',
        },
        reviews: {
            reviews: 'Reviews',
            reviewsCount: 'reviews',
            writeReview: 'Write a Review',
            yourRating: 'Your Rating',
            yourComment: 'Your Comment',
            commentPlaceholder: 'Share your experience...',
            selectRating: 'Select a rating',
            writeComment: 'Write a comment',
            reviewSubmitted: 'Review submitted!',
            questionSubmitted: 'Question submitted!',
            optional: 'optional',
            willBeQuestion: 'No rating = Question',
            yourQuestion: 'Your Question',
            questionPlaceholder: 'Ask a question about this product...',
            submit: 'Submit',
            reply: 'Reply',
            replyPlaceholder: 'Your reply...',
            replyAdded: 'Reply added',
            send: 'Send',
            loginToReview: 'Login to leave a review',
            loginToLike: 'Login to like',
            noReviews: 'No reviews yet. Be the first!',
            confirmDelete: 'Delete review?',
            deleted: 'Deleted',
            new: 'New',
            read: 'Read',
            replied: 'Replied',
            markAsRead: 'Mark as read',
        },
        admin: {
            title: 'Admin Panel',
            dashboard: 'Dashboard',
            products: 'Products',
            categories: 'Categories',
            orders: 'Orders',
            users: 'Users',
            backToSite: 'Back to Site',
            // Products
            addProduct: 'Add Product',
            editProduct: 'Edit Product',
            searchProducts: 'Search products...',
            productCount: 'products',
            variant: 'Variant',
            variants: 'Variants',
            addVariant: '+ Add Variant',
            color: 'Color',
            colorHex: 'HEX',
            stock: 'Stock',
            lowStock: 'Low Stock',
            images: 'Images',
            description: 'Description',
            // Categories
            addCategory: 'Add Category',
            editCategory: 'Edit Category',
            categoryName: 'Category Name',
            slug: 'Slug',
            // Orders
            orderNumber: 'Number',
            client: 'Client',
            phone: 'Phone',
            city: 'City',
            amount: 'Amount',
            date: 'Date',
            details: 'Details',
            orderDetails: 'Order Details',
            customer: 'Customer',
            delivery: 'Delivery',
            items: 'Items',
            allStatuses: 'All statuses',
            statusNew: 'New',
            statusReceived: 'Received',
            statusShipped: 'Shipped',
            statusDelivered: 'Delivered',
            statusCancelled: 'Cancelled',
            // Users
            searchUsers: 'Search by email, name...',
            user: 'User',
            email: 'Email',
            role: 'Role',
            registrationDate: 'Registration Date',
            all: 'All',
            admins: 'Admins',
            customers: 'Customers',
            roleAdmin: 'Admin',
            roleCustomer: 'Customer',
            makeAdmin: 'Make Admin',
            removeAdmin: 'Remove Admin',
            // Dashboard stats
            total: 'Total',
            newOrders: 'New Orders',
            totalProducts: 'Products',
            totalUsers: 'Users',
            totalRevenue: 'Revenue',
            recentOrders: 'Recent Orders',
            // Common
            productName: 'Product Name',
            price: 'Price',
            category: 'Category',
            status: 'Status',
            actions: 'Actions',
            search: 'Search...',
            save: 'Save',
            cancel: 'Cancel',
            delete: 'Delete',
            close: 'Close',
            noData: 'No data',
        },
        home: {
            heroTitle: 'Crafted with Love for Details',
            heroSubtitle: 'Premium handmade leather goods',
            viewCatalog: 'View Catalog',
            categories: 'Categories',
            bags: 'Bags',
            wallets: 'Wallets',
            belts: 'Belts',
            accessories: 'Accessories',
            freeDelivery: 'Free Delivery',
            freeDeliveryDesc: 'On orders over 2000₴',
            warranty: '2 Year Warranty',
            warrantyDesc: 'On all products',
            handmade: 'Handmade',
            handmadeDesc: 'Each item is unique',
            premiumQuality: 'Premium Quality',
            premiumQualityDesc: 'Only genuine leather',
            qualityTradition: 'Quality Tradition',
            qualityTraditionDesc: 'Over 10 years of experience in creating premium leather goods',
            satisfiedClients: 'Satisfied Clients',
            naturalLeather: 'Genuine Leather',
            warrantyYears: 'Warranty',
            aboutTitle: 'About Leder',
            aboutText1: 'We are a Ukrainian workshop creating the highest quality leather goods. Each item is handcrafted with attention to the smallest details.',
            aboutText2: 'We use only genuine Italian and Ukrainian tanned leather. Our products last for years, developing a noble patina over time.',
            feature1: 'Genuine Leather',
            feature2: 'Handmade',
            feature3: 'Quality Guarantee',
            feature4: 'Delivery across Ukraine',
            learnMore: 'Learn More',
            reviews: 'Customer Reviews',
            ctaTitle: 'Ready to Order?',
            ctaSubtitle: 'Browse the catalog and choose the best',
            goToCatalog: 'Go to Catalog',
        },
    },
    pl: {
        nav: {
            catalog: 'Katalog',
            bags: 'Torby',
            wallets: 'Portfele',
            belts: 'Paski',
            accessories: 'Akcesoria',
            about: 'O nas',
        },
        auth: {
            login: 'Zaloguj się',
            register: 'Rejestracja',
            logout: 'Wyloguj',
            profile: 'Mój profil',
            admin: 'Panel admina',
        },
        login: {
            title: 'Logowanie',
            subtitle: 'Witamy ponownie!',
            email: 'Email',
            password: 'Hasło',
            submit: 'Zaloguj się',
            noAccount: 'Nie masz konta?',
            createAccount: 'Utwórz konto',
        },
        register: {
            title: 'Rejestracja',
            subtitle: 'Utwórz swoje konto',
            firstName: 'Imię',
            lastName: 'Nazwisko',
            email: 'Email',
            password: 'Hasło',
            confirmPassword: 'Potwierdź hasło',
            submit: 'Zarejestruj się',
            hasAccount: 'Masz już konto?',
            loginLink: 'Zaloguj się',
            minPassword: 'Minimum 6 znaków',
            repeatPassword: 'Powtórz hasło',
        },
        cart: {
            cart: 'Koszyk',
            empty: 'Koszyk jest pusty',
            checkout: 'Zamówienie',
            total: 'Razem',
            clear: 'Wyczyść koszyk',
            continue: 'Kontynuuj zakupy',
        },
        checkout: {
            title: 'Zamówienie',
            contactInfo: 'Dane kontaktowe',
            firstName: 'Imię',
            lastName: 'Nazwisko',
            middleName: 'Drugie imię',
            email: 'Email',
            phone: 'Telefon',
            delivery: 'Dostawa (Nova Poshta)',
            city: 'Miasto',
            cityPlaceholder: 'Zacznij wpisywać nazwę miasta...',
            warehouse: 'Oddział',
            warehouseSelect: 'Wybierz oddział',
            payment: 'Płatność',
            paymentCod: 'Płatność przy odbiorze',
            paymentCard: 'Płatność kartą (Stripe)',
            yourOrder: 'Twoje zamówienie',
            toPay: 'Do zapłaty',
            submit: 'Potwierdź zamówienie',
            processing: 'Przetwarzanie...',
            savedDataTitle: 'Dane z Twojego profilu',
            savedDataMessage: 'Prosimy o sprawdzenie poprawności i aktualności danych',
        },
        profile: {
            personalData: 'Dane osobowe',
            firstName: 'Imię',
            lastName: 'Nazwisko',
            email: 'Email',
            phone: 'Telefon',
            save: 'Zapisz zmiany',
            orders: 'Zamówienia',
            security: 'Bezpieczeństwo',
            shippingAddress: 'Adres dostawy',
            savedCity: 'Zapisane miasto',
            savedWarehouse: 'Zapisany oddział',
            noOrders: 'Brak zamówień',
            orderNumber: 'Zamówienie',
        },
        product: {
            addToCart: 'Dodaj do koszyka',
            outOfStock: 'Brak w magazynie',
            inStock: 'Dostępny',
            color: 'Kolor',
            description: 'Opis',
        },
        catalog: {
            title: 'Katalog produktów',
            subtitle: 'Ręcznie robione produkty ze skóry naturalnej',
            search: 'Szukaj produktów...',
            filters: 'Filtry',
            categories: 'Kategorie',
            categoryBags: 'Torby',
            categoryWallets: 'Portfele',
            categoryAccessories: 'Akcesoria',
            categoryBelts: 'Paski',
            colors: 'Kolor',
            price: 'Cena',
            from: 'Od',
            to: 'Do',
            apply: 'Zastosuj',
            reset: 'Resetuj',
            found: 'Znaleziono',
            products: 'produktów',
            sortNew: 'Nowości',
            sortPriceAsc: 'Cena: rosnąco',
            sortPriceDesc: 'Cena: malejąco',
            sortName: 'Nazwa A-Z',
            noProducts: 'Nie znaleziono produktów',
        },
        common: {
            loading: 'Ładowanie...',
            save: 'Zapisz',
            cancel: 'Anuluj',
            delete: 'Usuń',
            edit: 'Edytuj',
            currency: 'UAH',
        },
        about: {
            title: 'O Leder',
            story: 'Nasza historia',
            values: 'Nasze wartości',
            quality: 'Jakość',
            craftsmanship: 'Rzemiosło',
        },
        footer: {
            tagline: 'Ręcznie robione wyroby skórzane. Stworzone z miłością na Ukrainie.',
            catalog: 'Katalog',
            bags: 'Torby',
            wallets: 'Portfele',
            belts: 'Paski',
            accessories: 'Akcesoria',
            information: 'Informacje',
            about: 'O nas',
            delivery: 'Dostawa i płatność',
            returns: 'Zwroty',
            support: 'Wsparcie',
            contacts: 'Kontakt',
            location: 'Kijów, Ukraina',
            rights: 'Wszelkie prawa zastrzeżone.',
        },
        reviews: {
            reviews: 'Opinie',
            reviewsCount: 'opinii',
            writeReview: 'Napisz opinię',
            yourRating: 'Twoja ocena',
            yourComment: 'Twój komentarz',
            commentPlaceholder: 'Podziel się swoim doświadczeniem...',
            selectRating: 'Wybierz ocenę',
            writeComment: 'Napisz komentarz',
            reviewSubmitted: 'Opinia dodana!',
            questionSubmitted: 'Pytanie wysłane!',
            optional: 'opcjonalnie',
            willBeQuestion: 'Bez oceny = Pytanie',
            yourQuestion: 'Twoje pytanie',
            questionPlaceholder: 'Zadaj pytanie o ten produkt...',
            submit: 'Wyślij',
            reply: 'Odpowiedz',
            replyPlaceholder: 'Twoja odpowiedź...',
            replyAdded: 'Odpowiedź dodana',
            send: 'Wyślij',
            loginToReview: 'Zaloguj się, aby zostawić opinię',
            loginToLike: 'Zaloguj się, aby polubić',
            noReviews: 'Brak opinii. Bądź pierwszy!',
            confirmDelete: 'Usunąć opinię?',
            deleted: 'Usunięto',
            new: 'Nowa',
            read: 'Przeczytana',
            replied: 'Z odpowiedzią',
            markAsRead: 'Oznacz jako przeczytane',
        },
        admin: {
            title: 'Panel administracyjny',
            dashboard: 'Pulpit',
            products: 'Produkty',
            categories: 'Kategorie',
            orders: 'Zamówienia',
            users: 'Użytkownicy',
            backToSite: 'Powrót do sklepu',
            // Products
            addProduct: 'Dodaj produkt',
            editProduct: 'Edytuj produkt',
            searchProducts: 'Szukaj produktów...',
            productCount: 'produktów',
            variant: 'Wariant',
            variants: 'Warianty',
            addVariant: '+ Dodaj wariant',
            color: 'Kolor',
            colorHex: 'HEX',
            stock: 'Stan mag.',
            lowStock: 'Niski stan',
            images: 'Zdjęcia',
            description: 'Opis',
            // Categories
            addCategory: 'Dodaj kategorię',
            editCategory: 'Edytuj kategorię',
            categoryName: 'Nazwa kategorii',
            slug: 'Slug',
            // Orders
            orderNumber: 'Numer',
            client: 'Klient',
            phone: 'Telefon',
            city: 'Miasto',
            amount: 'Kwota',
            date: 'Data',
            details: 'Szczegóły',
            orderDetails: 'Szczegóły zamówienia',
            customer: 'Klient',
            delivery: 'Dostawa',
            items: 'Produkty',
            allStatuses: 'Wszystkie statusy',
            statusNew: 'Nowy',
            statusReceived: 'Otrzymano',
            statusShipped: 'Wysłano',
            statusDelivered: 'Dostarczono',
            statusCancelled: 'Anulowano',
            // Users
            searchUsers: 'Szukaj po email, imieniu...',
            user: 'Użytkownik',
            email: 'Email',
            role: 'Rola',
            registrationDate: 'Data rejestracji',
            all: 'Wszystkie',
            admins: 'Administratorzy',
            customers: 'Klienci',
            roleAdmin: 'Administrator',
            roleCustomer: 'Klient',
            makeAdmin: 'Nadaj uprawnienia',
            removeAdmin: 'Usuń uprawnienia',
            // Dashboard stats
            total: 'Razem',
            newOrders: 'Nowe zamówienia',
            totalProducts: 'Produktów',
            totalUsers: 'Użytkowników',
            totalRevenue: 'Przychód',
            recentOrders: 'Ostatnie zamówienia',
            // Common
            productName: 'Nazwa produktu',
            price: 'Cena',
            category: 'Kategoria',
            status: 'Status',
            actions: 'Akcje',
            search: 'Szukaj...',
            save: 'Zapisz',
            cancel: 'Anuluj',
            delete: 'Usuń',
            close: 'Zamknij',
            noData: 'Brak danych',
        },
        home: {
            heroTitle: 'Stworzone z miłością do detali',
            heroSubtitle: 'Ręcznie robione wyroby skórzane premium',
            viewCatalog: 'Zobacz katalog',
            categories: 'Kategorie',
            bags: 'Torby',
            wallets: 'Portfele',
            belts: 'Paski',
            accessories: 'Akcesoria',
            freeDelivery: 'Darmowa dostawa',
            freeDeliveryDesc: 'Przy zamówieniu od 2000₴',
            warranty: 'Gwarancja 2 lata',
            warrantyDesc: 'Na wszystkie produkty',
            handmade: 'Ręcznie robione',
            handmadeDesc: 'Każdy produkt jest unikalny',
            premiumQuality: 'Jakość premium',
            premiumQualityDesc: 'Tylko naturalna skóra',
            qualityTradition: 'Tradycja jakości',
            qualityTraditionDesc: 'Ponad 10 lat doświadczenia w tworzeniu produktów skórzanych premium',
            satisfiedClients: 'Zadowolonych klientów',
            naturalLeather: 'Naturalna skóra',
            warrantyYears: 'Gwarancji',
            aboutTitle: 'O Leder',
            aboutText1: 'Jesteśmy ukraińskim warsztatem tworzącym wyroby skórzane najwyższej jakości. Każdy produkt jest ręcznie wykonany z dbałością o najmniejsze szczegóły.',
            aboutText2: 'Używamy tylko naturalnej skóry garbarni włoskich i ukraińskich. Nasze produkty służą latami, z czasem nabierając szlachetnej patyny.',
            feature1: 'Naturalna skóra',
            feature2: 'Ręcznie robione',
            feature3: 'Gwarancja jakości',
            feature4: 'Dostawa na Ukrainę',
            learnMore: 'Dowiedz się więcej',
            reviews: 'Opinie klientów',
            ctaTitle: 'Gotowy do zamówienia?',
            ctaSubtitle: 'Przeglądaj katalog i wybierz najlepsze',
            goToCatalog: 'Przejdź do katalogu',
        },
    },
};

export const useLanguageStore = create<LanguageStore>()(
    persist(
        (set) => ({
            language: 'uk',
            setLanguage: (language) => set({ language }),
        }),
        { name: 'language-storage' }
    )
);

export const useTranslations = () => {
    const { language } = useLanguageStore();
    return translations[language];
};
